/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hnretail.view;

import hnretail.dbutils.testConn;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.OutputStream;
import java.util.Properties;

/**
 *
 * @author abendezur
 */
public class Preferences extends javax.swing.JInternalFrame {

    /**
     * Creates new form Preferences
     */
    public Preferences() {
        initComponents();
        load_preferences();
    }

    public void load_preferences(){
        try{
            
            String path = System.getProperty("user.dir");
            //System.out.println(path+"\\src\\utils");
            File propertiesFile = new File(path+"\\src\\utils\\connection.properties");
        
            FileReader fileReader = new FileReader(propertiesFile);

            Properties props = new Properties();
            props.load(fileReader);
            
            DriverField.setText(props.getProperty("database.driver"));
            URLField.setText(props.getProperty("database.url"));
            UsernameField.setText(props.getProperty("database.user"));
            PasswordField.setText(props.getProperty("database.password"));        
            RetypeField.setText(props.getProperty("database.password"));                    
            char[] pass = PasswordField.getPassword();
            String passString = new String(pass);
            System.out.println("Este es el password "+ passString.toString()  );
            
        } catch(Exception e){
            System.out.println(e);
        }
        
    }
    
    public boolean todolleno(){
        boolean paso = true;
        if (DriverField.getText().trim().isEmpty()){
            paso = false;
            DriverField.requestFocus();
            DriverField.setBackground(Color.RED);
            return paso;            
        }
        if (URLField.getText().trim().isEmpty()){
            paso = false;
            URLField.requestFocus();
            URLField.setBackground(Color.RED);
            return paso;            
        }
        if (UsernameField.getText().trim().isEmpty()){
            paso = false;
            UsernameField.requestFocus();
            UsernameField.setBackground(Color.RED);
            return paso;            
        }       
        char[] pass = PasswordField.getPassword();
        String passString = new String(pass);
        char[] retype = RetypeField.getPassword();
        String retypeString = new String(retype); 
        System.out.println(passString);
        System.out.println(retypeString);
        if (!passString.equals(retypeString)){
            paso = false;
            AlertLabel.setText("Password y Retype deben de coincidir");
            AlertLabel.setBackground(Color.red);
            PasswordField.requestFocus();
            PasswordField.setBackground(Color.yellow);
            RetypeField.setBackground(Color.yellow);
            return paso;                        
        }                
        return paso;        
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DriverField = new javax.swing.JTextField();
        URLField = new javax.swing.JTextField();
        UsernameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        RetypeField = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        AlertLabel = new javax.swing.JLabel();

        setTitle("Preferencias");

        jLabel1.setText("Driver:");

        jLabel2.setText("Url:");

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        jLabel5.setText("Retype:");

        URLField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.setPreferredSize(new java.awt.Dimension(71, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Probar");
        jButton3.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(71, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Parametros de Conexion de Base de Datos");

        AlertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AlertLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(DriverField)
                                        .addComponent(URLField)
                                        .addComponent(UsernameField)
                                        .addComponent(PasswordField)
                                        .addComponent(RetypeField, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(DriverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(URLField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RetypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AlertLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void URLFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URLFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (todolleno()){
        try {
            String path = System.getProperty("user.dir");            
            Properties props = new Properties();
            char[] pass = PasswordField.getPassword();
            String passString = new String(pass);        
            props.setProperty("database.password", ""+passString);            
            props.setProperty("database.user", ""+UsernameField.getText());            
            props.setProperty("database.url", ""+URLField.getText());            
            props.setProperty("database.driver", DriverField.getText());            
            File f = new File(path+"\\src\\utils\\connection.properties");
            OutputStream out = new FileOutputStream( f );
            props.store(out, "Database Connection Parameters, Do not modify");
        } catch (Exception e ) {
                System.out.println(e);
        }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            System.out.println("ffff");
            testConn tC = new testConn();
            System.out.println("ffffeeeeeee");
            if (tC.canConnect("SoftwareData")){
                AlertLabel.setText("Conectado a Base de Datos");
            }else{
                AlertLabel.setText("No se pudo obtener una coneccion.");
            }
        } catch (Exception e){
            AlertLabel.setText("No se pudo obtener una coneccion.");
            System.out.println("ffffeeeeeee "+e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlertLabel;
    private javax.swing.JTextField DriverField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField RetypeField;
    private javax.swing.JTextField URLField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
