/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hnretail.view;

import hnretail.dml.dataAccess;
import hnretail.model.Proveedor;
import java.awt.Color;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abendezur
 */
public class Proveedores_regsearch extends javax.swing.JInternalFrame {

    /**
     * Creates new form proveedores_search
     */    
    dataAccess dA = new dataAccess();    
    private Object[][] tableData;
    
    public Proveedores_regsearch() {
        initComponents();
        load_table();
    }
    
    public void load_table(){
        String[] titulos = {"Codigo","Nombre","Direccion","Telefono","Pagina","Email","Contacto"};
        tableData = dA.fill_table("proveedor", "codigoProveedor,nombreProveedor,direccionProveedor,telefono,paginaweb,email,nombreContacto");
        DefaultTableModel dataModel = new DefaultTableModel(tableData,titulos);
        provsTable.setModel(dataModel);        
    }

    public void clearScreen()
    {
       nombreProv.setText("");
       direccionProv.setText("");
       telPro.setText("");
       webPro.setText("");
       emailPro.setText("");
       contactoPro.setText("");
    }
    
    public boolean todolleno(){
        boolean paso = true;
        if (nombreProv.getText().trim().isEmpty()){
            paso = false;
            nombreProv.requestFocus();
            nombreProv.setBackground(Color.RED);
            return paso;            
        }
        if (direccionProv.getText().trim().isEmpty()){
            paso = false;
            direccionProv.requestFocus();
            direccionProv.setBackground(Color.RED);
            return paso;            
        }
        if (telPro.getText().trim().isEmpty()){
            paso = false;
            telPro.requestFocus();
            telPro.setBackground(Color.RED);
            return paso;            
        }
        if (webPro.getText().trim().isEmpty()){
            paso = false;
            webPro.requestFocus();
            webPro.setBackground(Color.RED);
            return paso;            
        }
        if (emailPro.getText().trim().isEmpty()){
            paso = false;
            emailPro.requestFocus();
            emailPro.setBackground(Color.RED);
            return paso;            
        }
        if (contactoPro.getText().trim().isEmpty()){
            paso = false;
            contactoPro.requestFocus();
            contactoPro.setBackground(Color.RED);
            return paso;            
        }
        return paso;        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreProv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccionProv = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        telPro = new javax.swing.JTextField();
        webPro = new javax.swing.JTextField();
        emailPro = new javax.swing.JTextField();
        contactoPro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        provsTable = new javax.swing.JTable();

        setTitle("Registro de Proveedores");

        jLabel1.setText("Nombre");

        jLabel2.setText("Direccion");

        direccionProv.setColumns(20);
        direccionProv.setRows(5);
        jScrollPane1.setViewportView(direccionProv);

        jLabel3.setText("Telefono");

        jLabel4.setText("Pagina Web");

        jLabel5.setText("Email");

        jLabel6.setText("Contacto");

        webPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webProActionPerformed(evt);
            }
        });

        jButton1.setText("Registrar");
        jButton1.setMaximumSize(new java.awt.Dimension(75, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(53, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.setPreferredSize(new java.awt.Dimension(53, 23));

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        provsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(provsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel5)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel6))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(telPro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(webPro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailPro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contactoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(nombreProv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (todolleno()){              
            Proveedor prov = new Proveedor();
            prov.setNombre(nombreProv.getText());
            prov.setDireccion(direccionProv.getText());
            prov.setTelefono(telPro.getText());
            prov.setWebpage(webPro.getText());
            prov.setEmail(emailPro.getText());
            prov.setContacto(contactoPro.getText());
            dA = new dataAccess();
            if (dA.registra_proveedor(prov)){
                JOptionPane.showMessageDialog(null, "Listo", "Paso", JOptionPane.OK_OPTION);
                clearScreen();                
                load_table();
                nombreProv.requestFocus();
            }else {
                JOptionPane.showMessageDialog(null, "No se pudo Guardar", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }else {
            System.out.println("Nop no entro");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void webProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_webProActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dA.cierra_Acceso();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactoPro;
    private javax.swing.JTextArea direccionProv;
    private javax.swing.JTextField emailPro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreProv;
    private javax.swing.JTable provsTable;
    private javax.swing.JTextField telPro;
    private javax.swing.JTextField webPro;
    // End of variables declaration//GEN-END:variables
}
